From python:3.7

RUN pip install virtualenv
RUN VIRTUAl_ENV=/env
RUN virtualenv_venv -p python3
ENV PATH='$VIRTUAl_ENV/bin:$PATH"

WORKDIR .
ADD . .

# install dependencies:
RUN pip[ install - r requirements.txt

#Run the application
CMD["python", "rl_tp.ipynb"]