name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: python:3.7
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          jupyter nbconvert --to python nb
